spring:
  application:
    name: openai2

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mariadb://localhost:3306/wizvildb
    username: wizuser
    password: wizuser
    driver-class-name: org.mariadb.jdbc.Driver

upload:
  path: src/main/resources/static/uploads/

google:
  api-key: ${GOOGLE_API_KEY}
  cx: ${GOOGLE_CX}
