spring:
  application:
    name: openai2

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  path: src/main/resources/static/uploads/

google:
  api-key: ${GOOGLE_API_KEY}
  cx: ${GOOGLE_CX}
